###
POST https://api.registry.smartb.network/cccev/requirementsList
Content-Type: application/json

{

}

###
POST http://146.59.242.43:8080/requirementsList
Content-Type: application/json

{

}

###
POST http://localhost:8083/requirementsList
Content-Type: application/json

{

}

###

POST http://localhost:8083/about
Content-Type: application/json

{

}

###

POST http://localhost:8083/requirementsList
Content-Type: application/json

{

}

###

GET http://localhost:8083/api-docs