### version
GET {{urlbase}}/about

### version
GET {{urlbase}}/about


###
POST {{urlbase}}/requirementsList
Content-Type: application/json

{

}
###
POST{{urlbase}}/requirementListChildrenByType
Content-Type: application/json

{
  "identifiers": ["P1", "P2", "P3", "P4", "P5"],
  "type": "Activities"
}

###
POST{{urlbase}}/http://localhost:8083/requirementGetByIdentifier
Content-Type: application/json

{
  "identifier": "P1"
}