package cccev.s2.requirement.domain

import cccev.s2.requirement.domain.command.RequirementAddConceptsCommand
import cccev.s2.requirement.domain.command.RequirementAddEvidenceTypeListsCommand
import cccev.s2.requirement.domain.command.RequirementAddRequirementsCommand
import cccev.s2.requirement.domain.command.RequirementAddedConceptsEvent
import cccev.s2.requirement.domain.command.RequirementAddedEvidenceTypeListsEvent
import cccev.s2.requirement.domain.command.RequirementAddedRequirementsEvent
import cccev.s2.requirement.domain.command.RequirementCreateCommand
import cccev.s2.requirement.domain.command.RequirementCreatedEvent
import cccev.s2.requirement.domain.command.RequirementRemoveConceptsCommand
import cccev.s2.requirement.domain.command.RequirementRemoveEvidenceTypeListsCommand
import cccev.s2.requirement.domain.command.RequirementRemoveRequirementsCommand
import cccev.s2.requirement.domain.command.RequirementRemovedConceptsEvent
import cccev.s2.requirement.domain.command.RequirementRemovedEvidenceTypeListsEvent
import cccev.s2.requirement.domain.command.RequirementRemovedRequirementsEvent
import cccev.s2.requirement.domain.command.RequirementUpdateCommand
import cccev.s2.requirement.domain.command.RequirementUpdatedEvent

interface RequirementAggregate {
	suspend fun create(command: RequirementCreateCommand): RequirementCreatedEvent
	suspend fun update(command: RequirementUpdateCommand): RequirementUpdatedEvent
	suspend fun addRequirements(command: RequirementAddRequirementsCommand): RequirementAddedRequirementsEvent
	suspend fun removeRequirements(command: RequirementRemoveRequirementsCommand): RequirementRemovedRequirementsEvent
	suspend fun addConcepts(command: RequirementAddConceptsCommand): RequirementAddedConceptsEvent
	suspend fun removeConcepts(command: RequirementRemoveConceptsCommand): RequirementRemovedConceptsEvent
	suspend fun addEvidenceTypeLists(command: RequirementAddEvidenceTypeListsCommand): RequirementAddedEvidenceTypeListsEvent
	suspend fun removeEvidenceTypeLists(command: RequirementRemoveEvidenceTypeListsCommand): RequirementRemovedEvidenceTypeListsEvent
}
